# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
#stripe_api_key: sk_test_hhnZgxUzpid4PweuND5kNXXE
#stripe_publishable_key: pk_test_87LayhWLhTKpfeY88G6tdHAb
#


# Credentials for Aws
aws_access_key_id: 'AKIAJW5PUEBGBI7FCO7Q'
aws_secret_access_key: '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'
fog_directory: 'nextpakkweb'

test:
  secret_key: sk_test_hhnZgxUzpid4PweuND5kNXXE
  publishable_key: pk_test_87LayhWLhTKpfeY88G6tdHAb

development:
  secret_key: 'sk_test_nLk42ccRsK4SKyDfacbDwXdQ'
  publishable_key: 'pk_test_zsdgNpCpqgKJBOEqN9ojAKcJ'

  SENDGRID_USERNAME: 'app60015677@heroku.com'
  SENDGRID_PASSWORD: 'xx3ps2p55532'

production:
  secret_key: sk_live_PcxAqlYAk8ozmflrZgPGBm5N
  publishable_key: pk_live_3uSmVhCpCZCnXMaZPJ7m9tSc

  SENDGRID_USERNAME: 'app60015677@heroku.com'
  SENDGRID_PASSWORD: 'xx3ps2p55532'

  GMAIL_DOMAIN: 'gmail.com'
  GMAIL_USERNAME: 'lowellfortune@gmail.com'
  GMAIL_PASSWORD: 'Sp@tb3rry@n'

   